### ISSUE TITLE
Syncing with Kong Admin API

### ISSUE THREAD

**Issue by Vivekbhusal** [peerstream/serverless-plugin-kong#1]
Hi @mani-keerthi 
Thanks for this amazing plugin. I am planning to use it on my new project. Is it safe for production use?

**Comment by crrobinson14** [comment]
@Vivekbhusal As always with Open Source software, "safe" is up to you to determine! We are using it ourselves in production, but your mileage may vary.

**Comment by Vivekbhusal** [comment]
I am having some issues to get it working. `sls deploy` works with no issue but it doesn't make any changes on kong. Is there a way to check logs of the plugin? What is the best way to report the issue?
